[package]
name = "oidc4vp"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "MIT OR Apache-2.0"
description = "OpenID Connect for Verifiable Presentations"
repository = "https://github.com/spruceid/oidc4vp-rs/"
documentation = "https://docs.rs/oidc4vp/"

[dependencies]
jsonpath-rust = "0.2.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
ssi = { version = "0.6.0", default-features = false }
thiserror = "1.0.37"
lazy_static = "1.4.0"
url = "2.3.1"
rand = "0.8.5"
isomdl = { git = "https://github.com/spruceid/isomdl", rev = "485de1d" }
#isomdl = {path = "../isomdl"}
time = "0.3.21"
p256 = "0.13.2"
base64 = "0.13.1"
x509-cert = "0.2.3"
serde_cbor = "0.11.2"
anyhow = "1.0.71"
async-trait = "0.1.72"
reqwest = "0.11.18"
josekit = { git = "https://github.com/cobward/josekit-rs", rev = "635c8a7" }
base64url = "0.1.0"

[dev-dependencies]
serde_path_to_error = "0.1.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "1.2", features = ["v4", "serde", "js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uuid = { version = "1.2", features = ["v4", "serde"] }
